
<h3>Rights of Foreign Nations</h3>

<p>73. The soil of the earth from one end of the land to the other is the property of the people who inhabit it. By birthright the Ongwehonweh (Original beings) are the owners of the soil which they own and occupy and none other may hold it. The same law has been held from the oldest times.</p>
<p>The Great Creator has made us of the one blood and of the same soil he made us and as only different tongues constitute different nations he established different hunting grounds and territories and made boundary lines between them.</p>
<p>74. When any alien nation or individual is admitted into the Five Nations the admission shall be understood only to be a temporary one. Should the person or nation create loss, do wrong or cause suffering of any kind to endanger the peace of the Confederacy, the Confederate Lords shall order one of their war chiefs to reprimand him or them and if a similar offence is again committed the offending party or parties shall be expelled from the territory of the Five United Nations.</p>
<p>75. When a member of an alien nation comes to the territory of the Five Nations and seeks refuge and permanent residence, the Lords of the Nation to which he comes shall extend hospitality and make him a member of the nation. Then shall he be accorded equal rights and privileges in all matters except as after mentioned.</p>
<p>76. No body of alien people who have been adopted temporarily shall have a vote in the council of the Lords of the Confederacy, for only they who have been invested with Lordship titles may vote in the Council. Aliens have nothing by blood to make claim to a vote and should they have it, not knowing all the traditions of the Confederacy, might go against its Great Peace. In this manner the Great Peace would be endangered and perhaps be destroyed.</p>
<p>77. When the Lords of the Confederacy decide to admit a foreign nation and an adoption is made, the Lords shall inform the adopted nation that its admission is only temporary. They shall also say to the nation that it must never try to control, to interfere with or to injure the Five Nations nor disregard the Great Peace or any of its rules or customs. That in no way should they cause disturbance or injury. Then should the adopted nation disregard these injunctions, their adoption shall be annuled and they shall be expelled.</p>
<p>The expulsion shall be in the following manner: The council shall appoint one of their War Chiefs to convey the message of annulment and he shall say, "You (naming the nation) listen to me while I speak. I am here to inform you again of the will of the Five Nations' Council. It was clearly made known to you at a former time. Now the Lords of the Five Nations have decided to expel you and cast you out. We disown you now and annul your adoption. Therefore you must look for a path in which to go and lead away all your people. It was you, not we, who committed wrong and caused this sentence of annulment. So then go your way and depart from the territory of the Five Nations and from the Confederacy."</p>
<p>78. Whenever a foreign nation enters the Confederacy or accepts the Great Peace, the Five Nations and the foreign nation shall enter into an agreement and compact by which the foreign nation shall endeavor to pursuade other nations to accept the Great Peace.</p>
