
<h3>Rights of the People of the Five Nations</h3>

<p>93. Whenever a specially important matter or a great emergency is presented before the Confederate Council and the nature of the matter affects the entire body of the Five Nations, threatening their utter ruin, then the Lords of the Confederacy must submit the matter to the decision of their people and the decision of the people shall affect the decision of the Confederate Council. This decision shall be a confirmation of the voice of the people.</p>
<p>94. The men of every clan of the Five Nations shall have a Council Fire ever burning in readiness for a council of the clan. When it seems necessary for a council to be held to discuss the welfare of the clans, then the men may gather about the fire. This council shall have the same rights as the council of the women.</p>
<p>95. The women of every clan of the Five Nations shall have a Council Fire ever burning in readiness for a council of the clan. When in their opinion it seems necessary for the interest of the people they shall hold a council and their decisions and recommendations shall be introduced before the Council of the Lords by the War Chief for its consideration.</p>
<p>96. All the Clan council fires of a nation or of the Five Nations may unite into one general council fire, or delegates from all the council fires may be appointeed to unite in a general council for discussing the interests of the people. The people shall have the right to make appointments and to delegate their power to others of their number. When their council shall have come to a conclusion on any matter, their decision shall be reported to the Council of the Nation or to the Confederate Council (as the case may require) by the War Chief or the War Chiefs.</p>
<p>97. Before the real people united their nations, each nation had its council fires. Before the Great Peace their councils were held. The five Council Fires shall continue to burn as before and they are not quenched. The Lords of each nation in future shall settle their nation's affairs at this council fire governed always by the laws and rules of the council of the Confederacy and by the Great Peace.</p>
<p>98. If either a nephew or a niece see an irregularity in the performance of the functions of the Great Peace and its laws, in the Confederate Council or in the conferring of Lordship titles in an improper way, through their War Chief they may demand that such actions become subject to correction and that the matter conform to the ways prescribed by the laws of the Great Peace.</p>
