<h2>The Great Binding Law, Gayanashagowa</h2>

<p>1. I am Dekanawidah and with the Five Nations' Confederate Lords I plant the Tree of Great Peace. I plant it in your territory, Adodarhoh, and the Onondaga Nation, in the territory of you who are Firekeepers.</p>
<p>I name the tree the Tree of the Great Long Leaves. Under the shade of this Tree of the Great Peace we spread the soft white feathery down of the globe thistle as seats for you, Adodarhoh, and your cousin Lords.</p>
<p>We place you upon those seats, spread soft with the feathery down of the globe thistle, there beneath the shade of the spreading branches of the Tree of Peace. There shall you sit and watch the Council Fire of the Confederacy of the Five Nations, and all the affairs of the Five Nations shall be transacted at this place before you, Adodarhoh, and your cousin Lords, by the Confederate Lords of the Five Nations.</p>
<p>2. Roots have spread out from the Tree of the Great Peace, one to the north, one to the east, one to the south and one to the west. The name of these roots is The Great White Roots and their nature is Peace and Strength.</p>
<p>If any man or any nation outside the Five Nations shall obey the laws of the Great Peace and make known their disposition to the Lords of the Confederacy, they may trace the Roots to the Tree and if their minds are clean and they are obedient and promise to obey the wishes of the Confederate Council, they shall be welcomed to take shelter beneath the Tree of the Long Leaves.</p>
<p>We place at the top of the Tree of the Long Leaves an Eagle who is able to see afar. If he sees in the distance any evil approaching or any danger threatening he will at once warn the people of the Confederacy.</p>
<p>3. To you Adodarhoh, the Onondaga cousin Lords, I and the other Confederate Lords have entrusted the caretaking and the watching of the Five Nations Council Fire.</p>
<p>When there is any business to be transacted and the Confederate Council is not in session, a messenger shall be dispatched either to Adodarhoh, Hononwirehtonh or Skanawatih, Fire Keepers, or to their War Chiefs with a full statement of the case desired to be considered. Then shall Adodarhoh call his cousin (associate) Lords together and consider whether or not the case is of sufficient importance to demand the attention of the Confederate Council. If so, Adodarhoh shall dispatch messengers to summon all the Confederate Lords to assemble beneath the Tree of the Long Leaves.</p>
<p>When the Lords are assembled the Council Fire shall be kindled, but not with chestnut wood, and Adodarhoh shall formally open the Council.</p>
<p>Then shall Adodarhoh and his cousin Lords, the Fire Keepers, announce the subject for discussion.</p>
<p>The Smoke of the Confederate Council Fire shall ever ascend and pierce the sky so that other nations who may be allies may see the Council Fire of the Great Peace.</p>
<p>Adodarhoh and his cousin Lords are entrusted with the Keeping of the Council Fire.</p>
<p>4. You, Adodarhoh, and your thirteen cousin Lords, shall faithfully keep the space about the Council Fire clean and you shall allow neither dust nor dirt to accumulate. I lay a Long Wing before you as a broom. As a weapon against a crawling creature I lay a staff with you so that you may thrust it away from the Council Fire. If you fail to cast it out then call the rest of the United Lords to your aid.</p>
<p>5. The Council of the Mohawk shall be divided into three parties as follows: Tekarihoken, Ayonhwhathah and Shadekariwade are the first party; Sharenhowaneh, Deyoenhegwenh and Oghrenghrehgowah are the second party, and Dehennakrineh, Aghstawenserenthah and Shoskoharowaneh are the third party. The third party is to listen only to the discussion of the first and second parties and if an error is made or the proceeding is irregular they are to call attention to it, and when the case is right and properly decided by the two parties they shall confirm the decision of the two parties and refer the case to the Seneca Lords for their decision. When the Seneca Lords have decided in accord with the Mohawk Lords, the case or question shall be referred to the Cayuga and Oneida Lords on the opposite side of the house.</p>
<p>6. I, Dekanawidah, appoint the Mohawk Lords the heads and the leaders of the Five Nations Confederacy. The Mohawk Lords are the foundation of the Great Peace and it shall, therefore, be against the Great Binding Law to pass measures in the Confederate Council after the Mohawk Lords have protested against them.</p>
<p>No council of the Confederate Lords shall be legal unless all the Mohawk Lords are present.</p>
<p>7. Whenever the Confederate Lords shall assemble for the purpose of holding a council, the Onondaga Lords shall open it by expressing their gratitude to their cousin Lords and greeting them, and they shall make an address and offer thanks to the earth where men dwell, to the streams of water, the pools, the springs and the lakes, to the maize and the fruits, to the medicinal herbs and trees, to the forest trees for their usefulness, to the animals that serve as food and give their pelts for clothing, to the great winds and the lesser winds, to the Thunderers, to the Sun, the mighty warrior, to the moon, to the messengers of the Creator who reveal his wishes and to the Great Creator who dwells in the heavens above, who gives all the things useful to men, and who is the source and the ruler of health and life.</p>
<p>Then shall the Onondaga Lords declare the council open.</p>
<p>The council shall not sit after darkness has set in.</p>
<p>8. The Firekeepers shall formally open and close all councils of the Confederate Lords, and they shall pass upon all matters deliberated upon by the two sides and render their decision.</p>
<p>Every Onondaga Lord (or his deputy) must be present at every Confederate Council and must agree with the majority without unwarrantable dissent, so that a unanimous decision may be rendered.</p>
<p>If Adodarhoh or any of his cousin Lords are absent from a Confederate Council, any other Firekeeper may open and close the Council, but the Firekeepers present may not give any decisions, unless the matter is of small importance.</p>
<p>9. All the business of the Five Nations Confederate Council shall be conducted by the two combined bodies of Confederate Lords. First the question shall be passed upon by the Mohawk and Seneca Lords, then it shall be discussed and passed by the Oneida and Cayuga Lords. Their decisions shall then be referred to the Onondaga Lords, (Fire Keepers) for final judgement.</p>
<p>The same process shall obtain when a question is brought before the council by an individual or a War Chief.</p>
<p>10. In all cases the procedure must be as follows: when the Mohawk and Seneca Lords have unanimously agreed upon a question, they shall report their decision to the Cayuga and Oneida Lords who shall deliberate upon the question and report a unanimous decision to the Mohawk Lords. The Mohawk Lords will then report the standing of the case to the Firekeepers, who shall render a decision as they see fit in case of a disagreement by the two bodies, or confirm the decisions of the two bodies if they are identical. The Fire Keepers shall then report their decision to the Mohawk Lords who shall announce it to the open council.</p>
<p>11. If through any misunderstanding or obstinacy on the part of the Fire Keepers, they render a decision at variance with that of the Two Sides, the Two Sides shall reconsider the matter and if their decisions are jointly the same as before they shall report to the Fire Keepers who are then compelled to confirm their joint decision.</p>
<p>12. When a case comes before the Onondaga Lords (Fire Keepers) for discussion and decsion, Adodarho shall introduce the matter to his comrade Lords who shall then discuss it in their two bodies. Every Onondaga Lord except Hononwiretonh shall deliberate and he shall listen only. When a unanimous decision shall have been reached by the two bodies of Fire Keepers, Adodarho shall notify Hononwiretonh of the fact when he shall confirm it. He shall refuse to confirm a decision if it is not unanimously agreed upon by both sides of the Fire Keepers.</p>
<p>13. No Lord shall ask a question of the body of Confederate Lords when they are discussing a case, question or proposition. He may only deliberate in a low tone with the separate body of which he is a member.</p>
<p>14. When the Council of the Five Nation Lords shall convene they shall appoint a speaker for the day. He shall be a Lord of either the Mohawk, Onondaga or Seneca Nation.</p>
<p>The next day the Council shall appoint another speaker, but the first speaker may be reappointed if there is no objection, but a speaker's term shall not be regarded more than for the day.</p>
<p>15. No individual or foreign nation interested in a case, question or proposition shall have any voice in the Confederate Council except to answer a question put to him or them by the speaker for the Lords.</p>
<p>16. If the conditions which shall arise at any future time call for an addition to or change of this law, the case shall be carefully considered and if a new beam seems necessary or beneficial, the proposed change shall be voted upon and if adopted it shall be called, "Added to the Rafters".</p>
